"""Add date modified column

Revision ID: a41feed36130
Revises: 7e58c155a07c
Create Date: 2023-02-16 06:16:09.932840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41feed36130'
down_revision = '7e58c155a07c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_at')
    # ### end Alembic commands ###
