version: '2.16.0'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_DEVELOPMENT_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
  db_test:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${TEST_DATABASE_NAME}
      POSTGRES_USER: ${TEST_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
    ports:
      - ${DATABASE_TESTING_PORT}:${TEST_DATABASE_PORT}
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'uvicorn app.api.main:app --reload --host 0.0.0.0'
  #   ports:
  #     - ${APPLICATION_PORT}:8001
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  
  