version: '2.16.0'
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - ${HOST_DATABASE_PORT}:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn app.api.main:app --reload --host 0.0.0.0'
    ports:
      - ${HOST_APPLICATION_PORT}:8000
    volumes:
      - .:/app
    depends_on:
      - db
  
  